const API_URL="https://rqdkfvvubiccaybubmbd.supabase.co/functions/v1/neighborhood-selection";
const DOC_URL="https://rqdkfvvubiccaybubmbd.supabase.co/functions/v1/social-disorganization-assignment-doc";
const DATA_BASE="../data/";

const citySlug={NewOrleans:"neworleans",LA:"losangeles",Philadelphia:"philadelphia",Chicago:"chicago",Houston:"houston",SanFrancisco:"sanfrancisco",Atlanta:"atlanta",Milwaukee:"milwaukee",Detroit:"detroit",Denver:"denver",Seattle:"seattle"};
const variables=[
 {key:"poverty",title:"Poverty",mapTitle:"2020 Tract Poverty",prefix:"SDT_poverty",field:"poverty",legend:"sdt_poverty_legend.png",breaks:[10,20,30,40],colors:["#fee5d9","#fcae91","#fb6a4a","#de2d26","#a50f15"]},
 {key:"stability",title:"Residential Stability",mapTitle:"Residential Stability",prefix:"SDT_stability",field:"stability",legend:"sdt_stability_legend.png",breaks:[20,40,60,80],colors:["#f7fcf5","#c7e9c0","#74c476","#238b45","#00441b"]},
 {key:"heterogeneity",title:"Racial-Ethnic Heterogeneity",mapTitle:"Racial-Ethnic Heterogeneity",prefix:"SDT_heterogeneity",field:"re_het",legend:"sdt_heterogeneity_legend.png",breaks:[15,30,50,65],colors:["#f7fbff","#c6dbef","#6baed6","#2171b5","#08306b"]}
];

const lsuId=document.getElementById("lsuId"),loadButton=document.getElementById("loadButton"),lookupMessage=document.getElementById("lookupMessage"),projectContent=document.getElementById("projectContent"),cityName=document.getElementById("cityName"),neighborhoodOne=document.getElementById("neighborhoodOne"),neighborhoodTwo=document.getElementById("neighborhoodTwo"),variableSections=document.getElementById("variableSections"),mapStatus=document.getElementById("mapStatus"),buildDocument=document.getElementById("buildDocument"),documentStatus=document.getElementById("documentStatus");

let maps={},currentProject=null,readyMaps=new Set(),basemapState={},datasets={},legendCache={};

function baseStyle(){return{version:8,sources:{satellite:{type:"raster",tiles:["https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"],tileSize:256,attribution:"Tiles © Esri"},osm:{type:"raster",tiles:["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],tileSize:256,attribution:"© OpenStreetMap contributors"}},layers:[{id:"satellite",type:"raster",source:"satellite",layout:{visibility:"none"}},{id:"osm",type:"raster",source:"osm",layout:{visibility:"visible"}}]}}
function colorExpression(cfg){const e=["step",["to-number",["get",cfg.field],-999],cfg.colors[0]];cfg.breaks.forEach((b,i)=>e.push(b,cfg.colors[i+1]));return["case",["==",["to-number",["get",cfg.field],-999],-999],"rgba(0,0,0,0)",e]}
function setControls(ok){buildDocument.disabled=!ok;documentStatus.textContent=ok?"Ready to build your Word assignment.":"Maps must finish loading first."}
function destroyMaps(){Object.values(maps).forEach(m=>m.remove());maps={};readyMaps=new Set();basemapState={};setControls(false)}
function findFeatureByName(geojson,name){return geojson.features.find(f=>Object.values(f?.properties||{}).some(v=>String(v).trim()===name))}
function geomCoords(geometry,out=[]){const walk=v=>{if(!Array.isArray(v))return;if(typeof v[0]==="number"&&typeof v[1]==="number")out.push([v[0],v[1]]);else v.forEach(walk)};if(geometry)walk(geometry.coordinates);return out}
function bbox(feature){const c=geomCoords(feature.geometry);const xs=c.map(v=>v[0]),ys=c.map(v=>v[1]);return[Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)]}
function expandBox(b,f=.72){const w=b[2]-b[0],h=b[3]-b[1],px=Math.max(w*f,.006),py=Math.max(h*f,.006);return[b[0]-px,b[1]-py,b[2]+px,b[3]+py]}
function overlaps(a,b){return a[0]<=b[2]&&a[2]>=b[0]&&a[1]<=b[3]&&a[3]>=b[1]}
function filteredData(data,box){return{type:"FeatureCollection",features:data.features.filter(f=>{try{return overlaps(bbox(f),box)}catch{return false}})}}
function addFineZoom(map){map.scrollZoom.disable();map.getCanvas().addEventListener("wheel",e=>{if(!(e.ctrlKey||e.metaKey))return;e.preventDefault();e.stopPropagation();map.jumpTo({zoom:Math.max(0,Math.min(22,map.getZoom()+(e.deltaY<0?.08:-.08)))})},{passive:false})}
function updateBasemapButtons(key,mode){document.querySelectorAll(`[data-map-key="${key}"][data-basemap]`).forEach(b=>{b.classList.toggle("active",b.dataset.basemap===mode);b.setAttribute("aria-pressed",b.dataset.basemap===mode?"true":"false")})}
function setBasemap(key,mode){const map=maps[key];basemapState[key]=mode;updateBasemapButtons(key,mode);if(!map||!map.isStyleLoaded())return;map.setLayoutProperty("osm","visibility",mode==="street"?"visible":"none");map.setLayoutProperty("satellite","visibility",mode==="satellite"?"visible":"none");if(map.getLayer("tract-fill"))map.setPaintProperty("tract-fill","fill-opacity",1);map.triggerRepaint()}
function markReady(key){readyMaps.add(key);if(readyMaps.size===6){setControls(true);mapStatus.textContent="All six maps are ready. Adjust the framing as needed; the Word document will use the street basemap."}}
function createMap(container,cfg,data,neighborhood,key){const nbox=bbox(neighborhood),view=expandBox(nbox);const nearby=filteredData(data,view);const map=new maplibregl.Map({container,style:baseStyle(),interactive:true,attributionControl:true,canvasContextAttributes:{preserveDrawingBuffer:true}});map.addControl(new maplibregl.NavigationControl({showCompass:false}),"top-right");addFineZoom(map);map.on("load",()=>{map.addSource("tracts",{type:"geojson",data:nearby});map.addLayer({id:"tract-fill",type:"fill",source:"tracts",paint:{"fill-color":colorExpression(cfg),"fill-opacity":1}});map.addLayer({id:"tract-line",type:"line",source:"tracts",paint:{"line-color":"#777","line-width":.65,"line-opacity":.55}});map.addSource("neighborhood",{type:"geojson",data:{type:"FeatureCollection",features:[neighborhood]}});map.addLayer({id:"nh-halo",type:"line",source:"neighborhood",paint:{"line-color":"#ffffff","line-width":6,"line-opacity":.85}});map.addLayer({id:"nh-line",type:"line",source:"neighborhood",paint:{"line-color":"#111111","line-width":3.5}});map.fitBounds([[view[0],view[1]],[view[2],view[3]]],{padding:18,duration:0,maxZoom:14});setBasemap(key,"street");map.once("idle",()=>markReady(key));setTimeout(()=>{if(!readyMaps.has(key))markReady(key)},6500)});maps[key]=map;basemapState[key]="street"}
function figureNumber(vIndex,nIndex){return vIndex*2+nIndex+1}
function renderSections(){const[n1,n2]=currentProject.neighborhoods,city=currentProject.city.split(",")[0];variableSections.innerHTML=variables.map((v,vi)=>`<section class="variable-section"><div class="variable-header"><div><div class="figure-number">VARIABLE ${vi+1}</div><h2>${v.title}</h2><p>Compare the spatial distribution within and immediately surrounding both neighborhoods.</p></div></div><div class="map-grid">${[n1,n2].map((n,ni)=>{const key=`${v.key}-${ni+1}`,num=figureNumber(vi,ni);return`<article class="figure-card"><div class="figure-heading"><div><span class="figure-number">Figure ${num}</span><h3>${n}</h3></div><div class="figure-controls"><div class="basemap-toggle" role="group" aria-label="Figure ${num} basemap"><button type="button" class="basemap-option active" data-map-key="${key}" data-basemap="street">Street map</button><button type="button" class="basemap-option" data-map-key="${key}" data-basemap="satellite">Satellite</button></div></div></div><div class="map-shell"><div id="map-${key}" class="map" aria-label="${v.title} map for ${n}"></div></div><p class="caption">Figure ${num}. ${v.mapTitle} – ${n}, ${city}</p></article>`}).join("")}</div></section>`).join("");document.querySelectorAll("[data-map-key][data-basemap]").forEach(b=>b.addEventListener("click",()=>setBasemap(b.dataset.mapKey,b.dataset.basemap)))}
function sdtExportLegendConfig(cfg){const labels=cfg.key==="poverty"?["<10%","10–<20%","20–<30%","30–<40%","40%+"]:cfg.key==="stability"?["<20%","20–<40%","40–<60%","60–<80%","80%+"]:["<15","15–<30","30–<50","50–<65","65+"];return{title:cfg.title,rows:[{items:cfg.colors.map((color,i)=>({color,label:labels[i]}))}],note:cfg.key==="heterogeneity"?"Higher values indicate greater racial-ethnic heterogeneity.":""}}
async function loadDatasets(slug){const results=await Promise.all(variables.map(async v=>{const r=await fetch(`${DATA_BASE}${v.prefix}_${slug}.geojson`,{cache:"force-cache"});if(!r.ok)throw new Error(`Could not load ${v.title} map data.`);return[v.key,await r.json()]}));datasets=Object.fromEntries(results)}
function renderMaps(){const[n1,n2]=currentProject.neighborhoods,f1=findFeatureByName(currentProject.geojson,n1),f2=findFeatureByName(currentProject.geojson,n2);if(!f1||!f2)throw new Error("Your saved neighborhood boundaries could not be matched.");destroyMaps();renderSections();mapStatus.textContent="Rendering six maps…";requestAnimationFrame(()=>variables.forEach(v=>{createMap(`map-${v.key}-1`,v,datasets[v.key],f1,`${v.key}-1`);createMap(`map-${v.key}-2`,v,datasets[v.key],f2,`${v.key}-2`)}))}
async function loadProject(){const id=lsuId.value.trim();if(id.length<4){lookupMessage.textContent="Enter a valid LSU ID.";lsuId.focus();return}loadButton.disabled=true;lookupMessage.textContent="Loading your project and Social Disorganization data…";projectContent.classList.add("is-hidden");destroyMaps();try{const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"moduleLookup",lsuId:id})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||"Could not load your project.");const slug=citySlug[p.cityKey];if(!slug)throw new Error("Your city is not configured for this module.");currentProject=p;cityName.textContent=p.city;neighborhoodOne.textContent=p.neighborhoods[0];neighborhoodTwo.textContent=p.neighborhoods[1];await loadDatasets(slug);projectContent.classList.remove("is-hidden");renderMaps();lookupMessage.textContent=""}catch(e){console.error(e);lookupMessage.textContent=e.message}finally{loadButton.disabled=false}}
function waitForIdle(map){return new Promise(resolve=>{let done=false;const finish=()=>{if(!done){done=true;resolve()}};map.once("idle",finish);setTimeout(finish,2500)})}
function loadImage(url){if(legendCache[url])return legendCache[url];legendCache[url]=new Promise((resolve,reject)=>{const img=new Image();img.crossOrigin="anonymous";img.onload=()=>resolve(img);img.onerror=()=>reject(new Error("Could not load map legend."));img.src=url});return legendCache[url]}
function configForKey(key){return variables.find(v=>key.startsWith(v.key+"-"))}
async function captureMap(key){const map=maps[key],cfg=configForKey(key);if(!map||!cfg)throw new Error("Map is not ready.");const previous=basemapState[key]||"street";try{if(previous!=="street"){setBasemap(key,"street");await waitForIdle(map)}else await waitForIdle(map);map.triggerRepaint();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const src=map.getCanvas();const canvas=window.CC_EXPORT_LEGEND.compose(src,sdtExportLegendConfig(cfg));const blob=await new Promise((resolve,reject)=>canvas.toBlob(v=>v?resolve(v):reject(new Error("Could not export map image.")),"image/png"));return{blob,width:canvas.width,height:canvas.height}}finally{if(previous!=="street")setBasemap(key,previous)}}
function safe(v){return String(v||"").normalize("NFKD").replace(/[^a-zA-Z0-9_-]+/g,"_").replace(/^_+|_+$/g,"").toLowerCase()||"map"}
function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function blobToDataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error("Could not encode image."));r.readAsDataURL(blob)})}
async function figureData(image,width=520){return{data:await blobToDataUrl(image.blob),width,height:Math.round(width*image.height/image.width)}}
async function logoData(){const r=await fetch("../4091logo_bw.png");if(!r.ok)throw new Error("Could not load course logo.");return blobToDataUrl(await r.blob())}
async function buildWord(){if(!currentProject||readyMaps.size!==6)return;setControls(false);documentStatus.textContent="Capturing six street-map figures and building your Word document…";try{const keys=variables.flatMap(v=>[`${v.key}-1`,`${v.key}-2`]);const captured=await Promise.all(keys.map(captureMap));const figures=await Promise.all(captured.map(i=>figureData(i)));const logo=await logoData();const payload={lsuId:lsuId.value.trim(),project:currentProject,logo,figures:{povertyOne:figures[0],povertyTwo:figures[1],stabilityOne:figures[2],stabilityTwo:figures[3],heterogeneityOne:figures[4],heterogeneityTwo:figures[5]}};const r=await fetch(DOC_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok){const p=await r.json().catch(()=>({}));throw new Error(p.error||"The document generator returned an error.")}downloadBlob(await r.blob(),`${safe(lsuId.value)}_social_disorganization.docx`);documentStatus.textContent="Word assignment downloaded. Replace and delete all red/bracketed prompts before submitting."}catch(e){console.error(e);documentStatus.textContent=`Could not build the Word assignment. ${e.message}`}finally{setControls(true)}}

loadButton.addEventListener("click",loadProject);lsuId.addEventListener("keydown",e=>{if(e.key==="Enter")loadProject()});buildDocument.addEventListener("click",buildWord);