const API_URL="https://rqdkfvvubiccaybubmbd.supabase.co/functions/v1/neighborhood-selection";
const DOC_URL="https://rqdkfvvubiccaybubmbd.supabase.co/functions/v1/political-economy-assignment-doc";
const DATA_BASE="../data/";
const HMDA_DATA_VERSION="20260816-hmda-alltracts-v3";

const citySlug={NewOrleans:"neworleans",LA:"losangeles",Philadelphia:"philadelphia",Chicago:"chicago",Houston:"houston",SanFrancisco:"sanfrancisco",Atlanta:"atlanta",Milwaukee:"milwaukee",Detroit:"detroit",Denver:"denver",Seattle:"seattle"};
const palettes={
 eviction:["#fff5eb","#fdd0a2","#fdae6b","#e6550d","#a63603"],
 hmda:["#f2f0f7","#cbc9e2","#9e9ac8","#756bb1","#54278f"]
};

const lsuId=document.getElementById("lsuId"),loadButton=document.getElementById("loadButton"),lookupMessage=document.getElementById("lookupMessage"),projectContent=document.getElementById("projectContent"),cityName=document.getElementById("cityName"),neighborhoodOne=document.getElementById("neighborhoodOne"),neighborhoodTwo=document.getElementById("neighborhoodTwo"),figureSections=document.getElementById("figureSections"),mapStatus=document.getElementById("mapStatus"),buildDocument=document.getElementById("buildDocument"),documentStatus=document.getElementById("documentStatus");

let currentProject=null,evictionData=null,hmdaData=null,maps={},readyMaps=new Set(),classInfo={};

function baseStyle(){return{version:8,sources:{},layers:[{id:"background",type:"background",paint:{"background-color":"#ffffff"}}]}}
function num(v){if(v===null||v===undefined||v==="")return null;const n=Number(v);return Number.isFinite(n)?n:null}
function featureCollection(features){return{type:"FeatureCollection",features}}
function findFeatureByName(geojson,name){return geojson.features.find(f=>Object.values(f?.properties||{}).some(v=>String(v).trim()===name))}
function geomCoords(geometry,out=[]){const walk=v=>{if(!Array.isArray(v))return;if(typeof v[0]==="number"&&typeof v[1]==="number")out.push([v[0],v[1]]);else v.forEach(walk)};if(geometry)walk(geometry.coordinates);return out}
function bboxThing(thing){const fs=thing?.type==="FeatureCollection"?thing.features:[thing],c=[];fs.filter(Boolean).forEach(f=>geomCoords(f.geometry,c));if(!c.length)throw new Error("Could not determine map extent.");const xs=c.map(v=>v[0]),ys=c.map(v=>v[1]);return[Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)]}
function expandBox(b,f=.72){const w=b[2]-b[0],h=b[3]-b[1],px=Math.max(w*f,.006),py=Math.max(h*f,.006);return[b[0]-px,b[1]-py,b[2]+px,b[3]+py]}
function overlaps(a,b){return a[0]<=b[2]&&a[2]>=b[0]&&a[1]<=b[3]&&a[3]>=b[1]}
function filteredData(data,box){return featureCollection(data.features.filter(f=>{try{return overlaps(bboxThing(f),box)}catch{return false}}))}
function fit(map,b,padding=22,maxZoom=14){map.fitBounds([[b[0],b[1]],[b[2],b[3]]],{padding,duration:0,maxZoom})}
function addFineZoom(map){map.scrollZoom.disable();map.getCanvas().addEventListener("wheel",e=>{if(!e.ctrlKey)return;e.preventDefault();e.stopPropagation();map.jumpTo({zoom:Math.max(0,Math.min(22,map.getZoom()+(e.deltaY<0?.08:-.08)))})},{passive:false})}
function addNeighborhoodOutline(map,feature,prefix="nh",width=3.5){map.addSource(prefix,{type:"geojson",data:featureCollection([feature])});map.addLayer({id:`${prefix}-halo`,type:"line",source:prefix,paint:{"line-color":"#ffffff","line-width":width+3,"line-opacity":1}});map.addLayer({id:`${prefix}-line`,type:"line",source:prefix,paint:{"line-color":"#111111","line-width":width,"line-opacity":1}})}
function destroyMaps(){Object.values(maps).forEach(m=>m.remove());maps={};readyMaps=new Set();classInfo={};setControls(false)}
function setControls(ok){document.querySelectorAll(".download-map").forEach(b=>b.disabled=!ok);buildDocument.disabled=!ok;documentStatus.textContent=ok?"Ready to build your Word assignment.":"Maps must finish loading first."}
function markReady(key){readyMaps.add(key);if(readyMaps.size===4){setControls(true);mapStatus.textContent="All four maps are ready. Adjust the framing and inspect the spatial patterns as needed before building the Word document."}}

function sortedValues(data,field,{positive=false}={}){return data.features.map(f=>num(f?.properties?.[field])).filter(v=>v!==null&&(!positive||v>0)).sort((a,b)=>a-b)}
function quantile(sorted,q){if(!sorted.length)return 0;const p=(sorted.length-1)*q,b=Math.floor(p),r=p-b;return sorted[b+1]!==undefined?sorted[b]+r*(sorted[b+1]-sorted[b]):sorted[b]}
function uniqueAscending(values){const out=[];for(const v of values){const n=Number(v);if(Number.isFinite(n)&&(!out.length||n>out[out.length-1]+1e-9))out.push(n)}return out}
function fallbackBreaks(values,count=4){if(!values.length)return Array.from({length:count},(_,i)=>i+1);const min=values[0],max=values[values.length-1];if(max<=min)return Array.from({length:count},(_,i)=>min+(i+1));return Array.from({length:count},(_,i)=>min+(max-min)*(i+1)/(count+1))}
function hmdaBreaks(data){const v=sortedValues(data,"loanrate");let b=uniqueAscending([.2,.4,.6,.8].map(q=>quantile(v,q)));if(b.length<4)b=fallbackBreaks(v,4);return b.slice(0,4)}
function evictionPositiveBreaks(data){const v=sortedValues(data,"evictrate",{positive:true});let b=uniqueAscending([.25,.5,.75].map(q=>quantile(v,q)));if(b.length<3)b=fallbackBreaks(v,3);return b.slice(0,3)}
function fmt(v,d=1){const n=num(v);return n===null?"No data":`${n.toFixed(d)}%`}
function cleanBreak(v){if(Math.abs(v)>=10)return v.toFixed(1).replace(/\.0$/,'');return v.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')}

function evictionExpression(b){return["case",["any",["!",["has","evictrate"]],["==",["get","evictrate"],null]],"rgba(0,0,0,0)",["<=",["to-number",["get","evictrate"],0],0],palettes.eviction[0],["step",["to-number",["get","evictrate"],0],palettes.eviction[1],b[0],palettes.eviction[2],b[1],palettes.eviction[3],b[2],palettes.eviction[4]]]}
function hmdaExpression(b){return["case",["==",["get","_noOwner"],true],"#ffffff",["any",["!",["has","loanrate"]],["==",["get","loanrate"],null]],"rgba(0,0,0,0)",["step",["to-number",["get","loanrate"],-999],palettes.hmda[0],b[0],palettes.hmda[1],b[1],palettes.hmda[2],b[2],palettes.hmda[3],b[3],palettes.hmda[4]]]}

function evictionLegendItems(b){return[{c:palettes.eviction[0],t:"0%"},{c:palettes.eviction[1],t:`>0–${cleanBreak(b[0])}%`},{c:palettes.eviction[2],t:`>${cleanBreak(b[0])}–${cleanBreak(b[1])}%`},{c:palettes.eviction[3],t:`>${cleanBreak(b[1])}–${cleanBreak(b[2])}%`},{c:palettes.eviction[4],t:`>${cleanBreak(b[2])}%`}]}
function hmdaLegendItems(){return[{c:palettes.hmda[0],t:"Very Low"},{c:palettes.hmda[1],t:"Low"},{c:palettes.hmda[2],t:"Moderate"},{c:palettes.hmda[3],t:"High"},{c:palettes.hmda[4],t:"Very High"},{c:"#ffffff",pattern:true,t:"No data: 0 owner-occupied units"}]}
function hmdaCategory(v,b){const n=num(v);if(n===null)return "No data";if(n<b[0])return "Very Low";if(n<b[1])return "Low";if(n<b[2])return "Moderate";if(n<b[3])return "High";return "Very High"}
function legendHtml(title,items,note=""){return `<span class="legend-title">${title}</span>${items.map(i=>`<span class="legend-item"><span class="legend-swatch" style="${i.pattern?"background:repeating-linear-gradient(135deg,#fff 0,#fff 4px,#111 4px,#111 6px)":`background:${i.c}`}"></span><span>${i.t}</span></span>`).join("")}${note?`<span class="legend-note">${note}</span>`:""}`}

function popupHtml(type,p){if(type==="eviction")return `<div class="value-popup"><strong>Block group ${p.GEOID10||p.bgidfp10||""}</strong><dl><dt>2012–2016 pooled annual eviction rate</dt><dd>${fmt(p.evictrate,2)}</dd><dt>Percent renter</dt><dd>${fmt(p.prenter)}</dd><dt>Eviction filing rate</dt><dd>${fmt(p.filerate,2)}</dd></dl><small>Use renter share as context when interpreting zero or very low eviction rates.</small></div>`;if(p._noOwner===true||p._noOwner==="true")return `<div class="value-popup"><strong>Tract ${p.GEOID10||p.trctidfp10||""}</strong><dl><dt>Relative mortgage investment</dt><dd>No data</dd><dt>Owner-occupied units (2020)</dt><dd>0</dd></dl><small>No mortgage-investment rate can be calculated because the tract has 0 owner-occupied housing units.</small></div>`;return `<div class="value-popup"><strong>Tract ${p.GEOID10||p.trctidfp10||""}</strong><dl><dt>Relative mortgage investment</dt><dd>${hmdaCategory(p.loanrate,classInfo.hmda)}</dd></dl></div>`}
function addPopup(map,layerId,type){let activePopup=null,activeId=null;map.on("mouseenter",layerId,()=>map.getCanvas().style.cursor="pointer");map.on("mouseleave",layerId,()=>map.getCanvas().style.cursor="");map.on("click",layerId,e=>{const f=e.features?.[0];if(!f)return;const p=f.properties||{},id=String(p.GEOID10||p.bgidfp10||p.trctidfp10||"");if(activePopup&&id===activeId){activePopup.remove();activePopup=null;activeId=null;return}if(activePopup)activePopup.remove();activeId=id;activePopup=new maplibregl.Popup({closeButton:true,closeOnClick:false,maxWidth:"300px"}).setLngLat(e.lngLat).setHTML(popupHtml(type,p)).addTo(map);activePopup.on("close",()=>{activePopup=null;activeId=null})})}

function ensureNoOwnerPattern(map){if(map.hasImage("no-owner-hatch"))return;const size=12,canvas=document.createElement("canvas");canvas.width=size;canvas.height=size;const ctx=canvas.getContext("2d");ctx.fillStyle="#ffffff";ctx.fillRect(0,0,size,size);ctx.strokeStyle="#111111";ctx.lineWidth=1.6;for(let off=-size;off<size*2;off+=6){ctx.beginPath();ctx.moveTo(off,size);ctx.lineTo(off+size,0);ctx.stroke()}map.addImage("no-owner-hatch",ctx.getImageData(0,0,size,size),{pixelRatio:1})}
function addThematicLayer(map,data,type,breaks){
 map.addSource("thematic",{type:"geojson",data});
 const color=type==="eviction"?evictionExpression(breaks):hmdaExpression(breaks);
 map.addLayer({id:"thematic-fill",type:"fill",source:"thematic",paint:{"fill-color":color,"fill-opacity":1}});
 if(type==="hmda"){
   const noOwner=featureCollection(data.features.filter(f=>f?.properties?._noOwner===true));
   ensureNoOwnerPattern(map);
   map.addSource("hmda-no-owner",{type:"geojson",data:noOwner});
   map.addLayer({id:"hmda-no-owner-hatch",type:"fill",source:"hmda-no-owner",paint:{"fill-pattern":"no-owner-hatch","fill-opacity":1}});
 }
 map.addLayer({id:"thematic-line",type:"line",source:"thematic",paint:{"line-color":"#777777","line-width":.6,"line-opacity":.72}});
 addPopup(map,"thematic-fill",type)
}

function figureCard(num,title,caption,key,legend){return `<article class="figure-card"><div class="figure-heading"><div><span class="figure-number">Figure ${num}</span><h3>${title}</h3></div><div class="figure-controls"><button type="button" class="secondary small download-map" data-map-key="${key}" data-figure="${num}" disabled>Download PNG</button></div></div><div class="map-shell"><div id="map-${key}" class="map" aria-label="${title}"></div></div><div class="map-legend">${legend}</div><p class="caption">${caption}</p></article>`}
function renderSections(){const[n1,n2]=currentProject.neighborhoods,city=currentProject.city.split(",")[0],eb=classInfo.eviction,hb=classInfo.hmda;const eLegend=legendHtml("2012–2016 pooled annual eviction rate",evictionLegendItems(eb),"Positive eviction rates are divided into city-specific quartiles; zero is shown separately. Click a block group to see percent renter."),hLegend=legendHtml("Mortgage investment, 2018–2021",hmdaLegendItems(hb),"City-specific quintiles of 2018–2021 mortgage originations per 1,000 owner-occupied housing units (2020); the same breaks are used for both neighborhoods. Hatched tracts have 0 owner-occupied units and no calculable rate.");figureSections.innerHTML=`<section class="variable-section"><div class="variable-header"><div class="figure-number">HOUSING PRECARITY</div><h2>Eviction</h2><p>Compare forced housing instability within and immediately around your two neighborhoods using pooled 2012–2016 eviction rates. Click a block group to see its percent renter.</p></div><div class="figure-stack">${figureCard(1,n1,`Figure 1. 2012–2016 Pooled Annual Eviction Rate – ${n1}, ${city}`,"eviction-1",eLegend)}${figureCard(2,n2,`Figure 2. 2012–2016 Pooled Annual Eviction Rate – ${n2}, ${city}`,"eviction-2",eLegend)}</div></section><section class="variable-section"><div class="variable-header"><div class="figure-number">EXTERNAL INVESTMENT</div><h2>Mortgage Investment</h2><p>Compare the geography of external mortgage investment using 2018–2021 home-purchase mortgage originations standardized by the 2020 owner-occupied housing stock.</p></div><div class="figure-stack">${figureCard(3,n1,`Figure 3. Mortgage Investment, 2018–2021 – ${n1}, ${city}`,"hmda-1",hLegend)}${figureCard(4,n2,`Figure 4. Mortgage Investment, 2018–2021 – ${n2}, ${city}`,"hmda-2",hLegend)}</div></section>`;document.querySelectorAll(".download-map").forEach(b=>b.addEventListener("click",()=>downloadFigure(b.dataset.mapKey,Number(b.dataset.figure))))}
function createAssignmentMap(key,feature,type){const view=expandBox(bboxThing(feature),.72),data=filteredData(type==="eviction"?evictionData:hmdaData,view),breaks=type==="eviction"?classInfo.eviction:classInfo.hmda,map=new maplibregl.Map({container:`map-${key}`,style:baseStyle(),interactive:true,attributionControl:false,canvasContextAttributes:{preserveDrawingBuffer:true}});map.addControl(new maplibregl.NavigationControl({showCompass:false}),"top-right");addFineZoom(map);map.on("load",()=>{addThematicLayer(map,data,type,breaks);addNeighborhoodOutline(map,feature,"neighborhood",3.5);fit(map,view,22,14);map.once("idle",()=>markReady(key));setTimeout(()=>{if(!readyMaps.has(key))markReady(key)},6500)});maps[key]=map}
function renderMaps(){const[n1,n2]=currentProject.neighborhoods,n1f=findFeatureByName(currentProject.geojson,n1),n2f=findFeatureByName(currentProject.geojson,n2);if(!n1f||!n2f)throw new Error("Your saved neighborhood boundaries could not be matched.");destroyMaps();classInfo.eviction=evictionPositiveBreaks(evictionData);classInfo.hmda=hmdaBreaks(hmdaData);renderSections();mapStatus.textContent="Rendering political economy maps…";requestAnimationFrame(()=>{createAssignmentMap("eviction-1",n1f,"eviction");createAssignmentMap("eviction-2",n2f,"eviction");createAssignmentMap("hmda-1",n1f,"hmda");createAssignmentMap("hmda-2",n2f,"hmda")})}

async function loadDatasets(slug){
 const [e,h,d]=await Promise.all([
   fetch(`${DATA_BASE}pe_evict_${slug}.geojson`,{cache:"force-cache"}),
   fetch(`${DATA_BASE}pe_hmda_${slug}.geojson?v=${HMDA_DATA_VERSION}`,{cache:"force-cache"}),
   fetch(`${DATA_BASE}pe_denials_${slug}.geojson?v=${HMDA_DATA_VERSION}`,{cache:"force-cache"})
 ]);
 if(!e.ok)throw new Error(`Eviction data for this city are not available yet (${slug}).`);
 if(!h.ok)throw new Error(`HMDA data for this city are not available yet (${slug}).`);
 if(!d.ok)throw new Error(`HMDA tract scaffold for this city is not available yet (${slug}).`);
 const [evict,hmda,scaffold]=await Promise.all([e.json(),h.json(),d.json()]);
 if(!evict?.features?.length)throw new Error("The eviction file is empty.");
 if(!hmda?.features?.length)throw new Error("The HMDA file is empty.");
 const id=f=>String(f?.properties?.GEOID10||f?.properties?.trctidfp10||"");
 const hmdaIds=new Set(hmda.features.map(id).filter(Boolean));
 const noOwner=(scaffold?.features||[]).filter(f=>{const g=id(f);return g&&!hmdaIds.has(g)}).map(f=>({type:"Feature",geometry:f.geometry,properties:{GEOID10:f?.properties?.GEOID10||f?.properties?.trctidfp10||"",trctidfp10:f?.properties?.trctidfp10||f?.properties?.GEOID10||"",loanrate:null,_noOwner:true}}));
 evictionData=evict;
 hmdaData=featureCollection([...hmda.features,...noOwner]);
}
async function loadProject(){const id=lsuId.value.trim();if(id.length<4){lookupMessage.textContent="Enter a valid LSU ID.";lsuId.focus();return}loadButton.disabled=true;lookupMessage.textContent="Loading your project and political economy data…";projectContent.classList.add("is-hidden");destroyMaps();try{const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"moduleLookup",lsuId:id})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||"Could not load your project.");const slug=citySlug[p.cityKey];if(!slug)throw new Error("Your city is not configured for this module.");currentProject=p;cityName.textContent=p.city;neighborhoodOne.textContent=p.neighborhoods[0];neighborhoodTwo.textContent=p.neighborhoods[1];await loadDatasets(slug);projectContent.classList.remove("is-hidden");renderMaps();lookupMessage.textContent=""}catch(e){console.error(e);lookupMessage.textContent=e.message}finally{loadButton.disabled=false}}

function waitForIdle(map){return new Promise(resolve=>{let done=false;const finish=()=>{if(!done){done=true;resolve()}};map.once("idle",finish);setTimeout(finish,2500)})}
function legendForKey(key){if(key.startsWith("eviction"))return{title:"2012–2016 pooled annual eviction rate",items:evictionLegendItems(classInfo.eviction),note:"Positive rates: city-specific quartiles; zero shown separately."};return{title:"Mortgage investment, 2018–2021",items:hmdaLegendItems(classInfo.hmda),note:"City-specific quintiles; hatched = 0 owner-occupied units."}}
function drawExportSwatch(ctx,x,y,sw,s,item){ctx.save();ctx.fillStyle=item.c||"#ffffff";ctx.fillRect(x,y,sw,sw);if(item.pattern){ctx.beginPath();ctx.rect(x,y,sw,sw);ctx.clip();ctx.strokeStyle="#111111";ctx.lineWidth=Math.max(1,1.3*s);for(let off=-sw;off<sw*2;off+=5*s){ctx.beginPath();ctx.moveTo(x+off,y+sw);ctx.lineTo(x+off+sw,y);ctx.stroke()}}ctx.restore();ctx.strokeStyle="#777";ctx.lineWidth=1*s;ctx.strokeRect(x+.5*s,y+.5*s,sw-1*s,sw-1*s)}
function drawExportLegend(ctx,canvas,info,scale){const s=scale,pad=10*s,font=Math.max(9*s,9),small=Math.max(8*s,8),sw=11*s,lineH=17*s,width=235*s,height=(46+info.items.length*17+20)*s,x=canvas.width-width-12*s,y=canvas.height-height-12*s;ctx.save();ctx.fillStyle="#ffffff";ctx.fillRect(x,y,width,height);ctx.strokeStyle="#bdbdbd";ctx.lineWidth=1*s;ctx.strokeRect(x+.5*s,y+.5*s,width-1*s,height-1*s);ctx.fillStyle="#222";ctx.font=`600 ${font}px Arial,sans-serif`;ctx.fillText(info.title,x+pad,y+18*s);ctx.font=`${small}px Arial,sans-serif`;let yy=y+37*s;for(const item of info.items){drawExportSwatch(ctx,x+pad,yy-sw+2*s,sw,s,item);ctx.fillStyle="#333";ctx.fillText(item.t,x+pad+17*s,yy);yy+=lineH}ctx.fillStyle="#666";ctx.font=`${small}px Arial,sans-serif`;ctx.fillText(info.note,x+pad,yy+4*s);ctx.restore()}
async function captureMap(key){const map=maps[key];if(!map)throw new Error("Map is not ready.");await waitForIdle(map);map.triggerRepaint();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const src=map.getCanvas(),canvas=document.createElement("canvas");canvas.width=src.width;canvas.height=src.height;const ctx=canvas.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(src,0,0);drawExportLegend(ctx,canvas,legendForKey(key),Math.max(window.devicePixelRatio||1,1));const blob=await new Promise((resolve,reject)=>canvas.toBlob(v=>v?resolve(v):reject(new Error("Could not export map image.")),"image/png"));return{blob,width:canvas.width,height:canvas.height}}
function safe(v){return String(v||"").normalize("NFKD").replace(/[^a-zA-Z0-9_-]+/g,"_").replace(/^_+|_+$/g,"").toLowerCase()||"map"}
function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function downloadFigure(key,num){const b=document.querySelector(`.download-map[data-map-key="${key}"]`);b.disabled=true;mapStatus.textContent=`Exporting Figure ${num}…`;try{const image=await captureMap(key);downloadBlob(image.blob,`${safe(lsuId.value)}_pe_figure${num}.png`);mapStatus.textContent=`Figure ${num} downloaded.`}catch(e){console.error(e);mapStatus.textContent=`Could not export Figure ${num}. ${e.message}`}finally{b.disabled=false}}
function blobToDataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error("Could not encode image."));r.readAsDataURL(blob)})}
async function figureData(image,width=525){return{data:await blobToDataUrl(image.blob),width,height:Math.round(width*image.height/image.width)}}
async function logoData(){const r=await fetch("../4091logo_bw.png");if(!r.ok)throw new Error("Could not load course logo.");return blobToDataUrl(await r.blob())}
async function buildWord(){if(!currentProject||readyMaps.size!==4)return;setControls(false);documentStatus.textContent="Capturing four map figures and building your Word document…";try{const keys=["eviction-1","eviction-2","hmda-1","hmda-2"],captured=await Promise.all(keys.map(captureMap)),figures=await Promise.all(captured.map(i=>figureData(i))),logo=await logoData();const payload={lsuId:lsuId.value.trim(),project:currentProject,logo,figures:{evictionOne:figures[0],evictionTwo:figures[1],hmdaOne:figures[2],hmdaTwo:figures[3]}};const r=await fetch(DOC_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok){const p=await r.json().catch(()=>({}));throw new Error(p.error||"Could not build the Word document.")}downloadBlob(await r.blob(),`${safe(lsuId.value)}_political_economy.docx`);documentStatus.textContent="Word assignment downloaded."}catch(e){console.error(e);documentStatus.textContent=e.message}finally{setControls(true)}}

loadButton.addEventListener("click",loadProject);lsuId.addEventListener("keydown",e=>{if(e.key==="Enter")loadProject()});buildDocument.addEventListener("click",buildWord);setControls(false);
